"""Added in miss direction

Revision ID: 0c64a6c93717
Revises: 9b3749f733d6
Create Date: 2024-12-29 20:36:06.085556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c64a6c93717'
down_revision = '9b3749f733d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('tee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        # Set a default value for rows where tee_id is NULL
        op.execute('UPDATE rounds SET tee_id = 1 WHERE tee_id IS NULL')

    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miss_direction', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_column('miss_direction')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('tee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
