"""Added in subscrition fields to user db

Revision ID: 0c95a62149b5
Revises: deb86d2f7cdb
Create Date: 2025-01-20 20:03:17.187590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c95a62149b5'
down_revision = 'deb86d2f7cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('subscription_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('subscription_active')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
