"""Adding confirm into user model

Revision ID: 1430f2d8a194
Revises: 7b659d7fd273
Create Date: 2025-04-23 20:18:51.618597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1430f2d8a194'
down_revision = '7b659d7fd273'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add confirmed as NULLABLE with a server_default so existing rows get backfilled to True
    #    Also add confirmed_on with a timestamp default if you want to record when they were marked.
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column(
            'confirmed',
            sa.Boolean(),
            nullable=True,
            server_default=sa.text('1')           # SQLite uses 1 for TRUE
        ))
        batch_op.add_column(sa.Column(
            'confirmed_on',
            sa.DateTime(),
            nullable=True,
            server_default=sa.text('CURRENT_TIMESTAMP')
        ))

    # 2) Safety-net backfill (in case any NULLs slipped through)
    op.execute(
        "UPDATE users SET confirmed = 1 WHERE confirmed IS NULL"
    )
    op.execute(
        "UPDATE users SET confirmed_on = CURRENT_TIMESTAMP WHERE confirmed_on IS NULL"
    )

    # 3) Rebuild the table to enforce NOT NULL on confirmed and drop its default;
    #    leave confirmed_on nullable (or drop its default if you prefer)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'confirmed',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=None
        )
        # If you want to keep confirmed_on nullable but remove its default:
        batch_op.alter_column(
            'confirmed_on',
            existing_type=sa.DateTime(),
            nullable=True,
            server_default=None
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
