"""Course Par

Revision ID: 3285541caa52
Revises: a9876abeaf3e
Create Date: 2024-12-25 11:54:17.713734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3285541caa52'
down_revision = 'a9876abeaf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_courses')
    with op.batch_alter_table('tees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_par', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tees', schema=None) as batch_op:
        batch_op.drop_column('course_par')

    op.create_table('_alembic_tmp_courses',
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
