"""Added shots

Revision ID: 42a194cfe674
Revises: 860c90311637
Create Date: 2024-12-26 09:38:33.611361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a194cfe674'
down_revision = '860c90311637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('shotID', sa.Integer(), nullable=False),
    sa.Column('roundID', sa.Integer(), nullable=False),
    sa.Column('holeID', sa.Integer(), nullable=False),
    sa.Column('distance_before', sa.Float(), nullable=False),
    sa.Column('lie_before', sa.String(length=50), nullable=False),
    sa.Column('distance_after', sa.Float(), nullable=True),
    sa.Column('lie_after', sa.String(length=50), nullable=True),
    sa.Column('shot_type', sa.String(length=50), nullable=False),
    sa.Column('strokes_gained', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['holeID'], ['holes.holeID'], ),
    sa.ForeignKeyConstraint(['roundID'], ['rounds.roundID'], ),
    sa.PrimaryKeyConstraint('shotID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    # ### end Alembic commands ###
