"""unique user id

Revision ID: 661d7cf2084e
Revises: bb0dee721284
Create Date: 2025-04-01 22:41:02.731809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661d7cf2084e'
down_revision = 'bb0dee721284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
