"""Added a holestats table

Revision ID: 6fed57f14c08
Revises: 8f2a1d389464
Create Date: 2024-12-30 11:32:00.767015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fed57f14c08'
down_revision = '8f2a1d389464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hole_stats',
    sa.Column('holeStatsID', sa.Integer(), nullable=False),
    sa.Column('roundID', sa.Integer(), nullable=False),
    sa.Column('holeID', sa.Integer(), nullable=False),
    sa.Column('gir', sa.Boolean(), nullable=True),
    sa.Column('fairway_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['holeID'], ['holes.holeID'], ),
    sa.ForeignKeyConstraint(['roundID'], ['rounds.roundID'], ),
    sa.PrimaryKeyConstraint('holeStatsID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hole_stats')
    # ### end Alembic commands ###
