"""Added club column to Shot model

Revision ID: 7ee07eb89202
Revises: a0873aa9f251
Create Date: 2025-04-14 22:31:29.023538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee07eb89202'
down_revision = 'a0873aa9f251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_sided', sa.Boolean(), nullable=True))



    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_column('short_sided')

    # ### end Alembic commands ###
