"""Added in relations

Revision ID: 860c90311637
Revises: e369dd07a559
Create Date: 2024-12-25 20:28:51.225742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c90311637'
down_revision = 'e369dd07a559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_hole_tee", 'tees', ['teeID'], ['teeID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
