"""Added in sg into rounds

Revision ID: 8f2a1d389464
Revises: 0c64a6c93717
Create Date: 2024-12-30 11:29:05.182903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2a1d389464'
down_revision = '0c64a6c93717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sg_off_tee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sg_approach', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sg_around_green', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sg_putting', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('sg_putting')
        batch_op.drop_column('sg_around_green')
        batch_op.drop_column('sg_approach')
        batch_op.drop_column('sg_off_tee')

    # ### end Alembic commands ###
