"""nullable

Revision ID: 9be3aeb79c23
Revises: d136ee453083
Create Date: 2025-01-15 22:11:54.720900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be3aeb79c23'
down_revision = 'd136ee453083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('round_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('round_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
