"""Add users table

Revision ID: a9876abeaf3e
Revises: 
Create Date: 2024-12-22 14:08:07.707578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9876abeaf3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('courseID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('holes',
    sa.Column('holeID', sa.Integer(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseID'], ['courses.courseID'], ),
    sa.PrimaryKeyConstraint('holeID')
    )
    op.create_table('rounds',
    sa.Column('roundID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.courseID'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('roundID')
    )
    op.create_table('tees',
    sa.Column('teeID', sa.Integer(), nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseID'], ['courses.courseID'], ),
    sa.PrimaryKeyConstraint('teeID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tees')
    op.drop_table('rounds')
    op.drop_table('holes')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
