"""Added in new columns

Revision ID: ce9c7792216a
Revises: 6fed57f14c08
Create Date: 2024-12-30 16:05:55.574949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9c7792216a'
down_revision = '6fed57f14c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('up_and_down', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hole_score', sa.Integer()))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer()))
        batch_op.add_column(sa.Column('score_to_par', sa.Integer()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128)))
        batch_op.add_column(sa.Column('last_name', sa.String(length=128)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('score_to_par')
        batch_op.drop_column('score')

    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.drop_column('hole_score')
        batch_op.drop_column('up_and_down')

    # ### end Alembic commands ###
