"""Added in round type to data base

Revision ID: d136ee453083
Revises: ce9c7792216a
Create Date: 2025-01-15 18:46:30.107287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd136ee453083'
down_revision = 'ce9c7792216a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('round_type')

    # ### end Alembic commands ###
