"""changed nulls

Revision ID: deb86d2f7cdb
Revises: 6216a0f33185
Create Date: 2025-01-17 13:15:24.618524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb86d2f7cdb'
down_revision = '6216a0f33185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.alter_column('fairway_hit',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('up_and_down',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.alter_column('up_and_down',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('fairway_hit',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
