"""Score to par nullable

Revision ID: e08ac0957c58
Revises: 9be3aeb79c23
Create Date: 2025-01-16 20:06:10.932718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08ac0957c58'
down_revision = '9be3aeb79c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.alter_column('gir',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('fairway_hit',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('up_and_down',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hole_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.alter_column('distance_after',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('lie_after',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('strokes_gained',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.alter_column('strokes_gained',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('lie_after',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('distance_after',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('score_to_par',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hole_stats', schema=None) as batch_op:
        batch_op.alter_column('hole_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('up_and_down',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('fairway_hit',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('gir',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
