"""Added tee relation

Revision ID: e369dd07a559
Revises: 3285541caa52
Create Date: 2024-12-25 20:09:04.463676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e369dd07a559'
down_revision = '3285541caa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teeID', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holes', schema=None) as batch_op:
        batch_op.drop_column('teeID')

    # ### end Alembic commands ###
